### ISSUE TITLE
Unable to import sys_56.sql

### ISSUE THREAD

**Issue by wendellsulad** [MarkLeith/mysql-sys#100]
I have an issue while importing sys_56.sql with the latest version in github
My current mysql version I have used is mysql 5.6.20 with redhat 6.5 linux os

Below is my my.cnf configuration for performance schema
performance_schema
performance_schema_instrument = '%=on'
performance_schema_consumer_events_stages_current = ON
performance_schema_consumer_events_stages_history = ON
performance_schema_consumer_events_stages_history_long = ON
performance_schema_consumer_events_statements_current = ON
performance_schema_consumer_events_statements_history = ON
performance_schema_consumer_events_statements_history_long = ON
performance_schema_consumer_events_waits_current = ON
performance_schema_consumer_events_waits_history = ON
performance_schema_consumer_events_waits_history_long = ON
performance_schema_consumer_global_instrumentation = ON
performance_schema_consumer_thread_instrumentation = ON
performance_schema_consumer_statements_digest = ON

Upon importing sys_56.sql below is the sql error that I've encoutered.

[user1@server-local mysql-sys-master]# mysql -u root -p < ./sys_56.sql
Enter password:
ERROR 1146 (42S02) at line 47 in file: './views/p_s/processlist.sql': Table 'performance_schema.threads' doesn't exist

**Comment by JesperWisborgKrogh** [comment]
Was MySQL upgraded (RHEL 6 ships with MySQL 5.1 I believe)? If so make sure to execute mysql_upgrade first before installing the sys schema. You should also check your MySQL error log to see if there are any messages. If there are messages such as:

120426 17:08:33 [ERROR] Native table 'performance_schema'.'events_waits_current' has the wrong structure

that is a sure sign that mysql_upgrade needs to be executed.

You can also check:

     mysql> SHOW GLOBAL VARIABLES LIKE 'performance%';
     mysql> SHOW TABLES FROM performance_schema;

Note: the performance_schema.threads table was added in 5.5.6 (though changed in 5.5.8 and greatly changed sometime pre-GA in 5.6). So the table is present in all MySQL 5.6 releases whenever the Performance Schema is compiled in and the database is installed with mysql_install_db from 5.6 or mysql_upgrade has been executed successfully for an instance installed earlier.

**Comment by wendellsulad** [comment]
Thanks a lot  I have successfully executed after performing mysql_upgrade.
