### ISSUE TITLE
If one of the tables in sys schema is polled at regular intervals then it skews the output from the view x$ps_digest_95th_percentile_by_avg_us

### ISSUE THREAD

**Issue by ovaistariq** [MarkLeith/mysql-sys#45]
The view `x$ps_digest_95th_percentile_by_avg_us` lists the 95th percentile runtime for all statements, which makes it a good candidate to be polled by an external check such as this https://github.com/ovaistariq/datadog-agent-checks/blob/master/mysql_sys.py for the purpose of monitoring the runtime of the queries.
However, polling it often causes it to skew the result of this table because `sys`.`x$ps_digest_95th_percentile_by_avg_us` makes up a good chunk of the queries executed.

Can we have the x$ps_digest_avg_latency_distribution view ignore the tables in the sys schema?

**Comment by ovaistariq** [comment]
I was able to get around the issue by changing the datadog agent check to query performance_schema directly:
https://github.com/ovaistariq/dd-agent/blob/mysql_ps_check-issue_1283/checks.d/mysql_ps.py

Line 102 to 114 is the SQL that I used which is basically the same SQL that you setup as views in sys schema. PS does not track these SELECT queries. That is why I was wondering if same can be done with the sys schema. 
But I agree if this is causing overhead then it needs to be dealt with and I cannot come up with the right general solution.

**Comment by MarkLeith** [comment]
I'm not sure you are right that P_S will not track SELECTs that are directly against P_S (it does, it doesn't filter out any statements at all, unless the digest table is full). It's probably just that they don't show near the top when executed directly (there's overhead in reading the view definitions etc.).

As you've worked around it for now, I'm going to close this issue - I don't want to filter anything out of the views for now.

**Comment by ovaistariq** [comment]
There are actually no statements in `events_statements_summary_by_digest` except for the TRUNCATE table statement that gets execute periodically to reset the `events_statements_summary_by_digest` table. I would expect the SELECTs executed against the table `events_statements_summary_by_digest` to be logged since they are executed so frequently (every 15s).

After thinking about filtering of statements, I agree with you about not filtering anything, since that mask things from the workload that are caused by frequently accessing the `sys` schema.
