### ISSUE TITLE
5.7 processlist view should show progress

### ISSUE THREAD

**Issue by morgo** [MarkLeith/mysql-sys#50]
5.7.6 added stages to performance schema.

It would be nice if the processlist view showed an extra column after 'current_statement' called 'progress'.  The obvious use case that I'm looking at is for an `ALTER TABLE` command.

**Comment by MarkLeith** [comment]
Fixed in 1.5.0:

https://github.com/MarkLeith/mysql-sys/commit/0121897bc5ab0ab79c5a9ab57135fdcca5990182
