### ISSUE TITLE
generate_sql_file broken in 1.4.0

### ISSUE THREAD

**Issue by gitsno** [MarkLeith/mysql-sys#51]
The change to before_setup.sql to update the version to 1.4.0 breaks generate_sql_file because it sets the DEFINER to root@localhost.

**Comment by nadavsr** [comment]
+1, unable to use it on RDS.

```
➜  mysql-sys git:(master) ./generate_sql_file.sh -v 56 -b -u CURRENT_USER  

    Wrote file: /tmp/mysql-sys/sys_1.4.0_56_inline.sql
Object Definer: CURRENT_USER
   sql_log_bin: disabled

➜  mysql-sys git:(master) ✗ mysql -uroot -hdb2 -p < ./sys_1.4.0_56_inline.sql
Enter password: 
ERROR 1227 (42000) at line 22: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```

**Comment by gitsno** [comment]
nadavsr - the workaround is simple, in the file named before_setup.sql, just replace this line
`CREATE OR REPLACE ALGORITHM = MERGE DEFINER = 'root'@'localhost' SQL SECURITY INVOKER VIEW version AS SELECT '1.4.0' AS sys_version, version() AS mysql_version;`
with
`CREATE OR REPLACE VIEW version AS SELECT '1.4.0' AS sys_version, version() AS mysql_version;`
then run the generate again and the resulting script will work. 
(You could also find that line in the script you already generated and replace it)

**Comment by rinatio** [comment]
+1

**Comment by MarkLeith** [comment]
Fix committed to the development branch, will be a part of the 1.5.0 release:

https://github.com/MarkLeith/mysql-sys/commit/6aa976d75575a4a350a48c9abd9555ef7bb5c5cb
