### ISSUE TITLE
Comment for format_statement function

### ISSUE THREAD

**Issue by gitsno** [MarkLeith/mysql-sys#52]
This is very minor but in the COMMENT for the format_statement function the following line uses an apostrophe
`Formats a normalized statement, truncating it if it\'s > 64 characters long by default.`
The apostrophe is escaped and should not be an issue, but in some clients (in my case Toad for MySQL) it isn't handled quite correctly. I will try to get the issue fixed in the client, but I'd like to also suggest removing the apostrophe from the COMMENT and changing the line to 
`Formats a normalized statement, truncating it if it is > 64 characters long by default.`

**Comment by gitsno** [comment]
In fact I'll revise the suggestion, using two single quotes instead of the `\'` works just fine (which I think is more common in SQL anyway), so can that line in the comment simply be changed to
`Formats a normalized statement, truncating it if it''s > 64 characters long by default.`

**Comment by MarkLeith** [comment]
Fix pushed in to the 1.5.0 release.
