### ISSUE TITLE
Userfriendly time in sys.processlist

### ISSUE THREAD

**Issue by dveeden** [MarkLeith/mysql-sys#60]
In the sys.processlist the time could be made more userfriendly.

```sql
select *,format_time(time*1000000000000) as time_fmt from processlist\G
```

```
                  time: 1111
              time_fmt: 00:18:31.00
```

If I understand it correctly this should be done to processlist and not to x$processlist

**Comment by MarkLeith** [comment]
Fixed in 1.5.0:

https://github.com/MarkLeith/mysql-sys/commit/0121897bc5ab0ab79c5a9ab57135fdcca5990182
