### ISSUE TITLE
v.5.5 :(

### ISSUE THREAD

**Issue by ericdp** [MarkLeith/mysql-sys#64]
Is there a version of mysql-sys for MySQL Community v.5.5?  At work this is the version I have to work with and there are no plans to upgrade. 

Thanks
Eric

**Comment by MarkLeith** [comment]
Unfortunately not, I stopped support for 5.5 when I moved from ps_helper/dbahelper to sys. You can get a legacy 5.5 version here though:

https://github.com/MarkLeith/dbahelper
