### ISSUE TITLE
GROUP BY error when importing sys_56.sql

### ISSUE THREAD

**Issue by joshlawrence** [MarkLeith/mysql-sys#65]
When importing sys_56.sql, I receive this error message:

`ERROR 1055 (42000) at line 47 in file: './views/p_s/processlist.sql': 'performance_schema.pps.PROCESSLIST_ID' isn't in GROUP BY`

Running Percona Server 5.6, here's the output of `mysql --version`:

`mysql  Ver 14.14 Distrib 5.6.24-72.2, for debian-linux-gnu (x86_64) using  6.2`

I'm just now learning this software, so I'm very unfamiliar with the installation process.  If I'm leaving out information that you need, please let me know.

**Comment by MarkLeith** [comment]
This was recently fixed via Issue #56, and is pushed to the development branch:

https://github.com/MarkLeith/mysql-sys/commit/7e677dc98c7c482c5d58896a3d01ef8970185ca9

Will be a part of the 1.5.0 release, but for now you can use the development branch to install.
